### PR TITLE
Fix email OTP authenticator to handle federated users in a proper way.

### LINKED ISSUE #4242: Email OTP Authenticator does not work with multi-step authentication
**Steps to reproduce**

Configure service provider with 3 step authentication scheme as following

    Identifier first authenticator
    Basic + Federated authenticator (2 options)
    email OTP authenticator

below error trace is occuring when trying federated authentication

```
    [2018-12-24 11:38:23,257] ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -   Failed to process EmailOTP flow 
    org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException:  Failed to process EmailOTP flow 
    	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.proceedOTPWithFederatedEmailAddress(EmailOTPAuthenticator.java:583)
    	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.processEmailOTPMandatory(EmailOTPAuthenticator.java:400)
    	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.initiateAuthenticationRequest(EmailOTPAuthenticator.java:191)
    	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.process(EmailOTPAuthenticator.java:123)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.doAuthentication(DefaultStepHandler.java:500)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler.handle(DefaultStepHandler.java:265)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.DefaultStepBasedSequenceHandler.handle(DefaultStepBasedSequenceHandler.java:185)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.sequence.impl.GraphBasedSequenceHandler.handle(GraphBasedSequenceHandler.java:109)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultAuthenticationRequestHandler.handle(DefaultAuthenticationRequestHandler.java:139)
    	at org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator.handle(DefaultRequestCoordinator.java:187)
    	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doPost(CommonAuthenticationServlet.java:53)
    	at org.wso2.carbon.identity.application.authentication.framework.servlet.CommonAuthenticationServlet.doGet(CommonAuthenticationServlet.java:43)
    ...
    Caused by: org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: There is no email claim to send otp
    	at org.wso2.carbon.identity.authenticator.emailotp.EmailOTPAuthenticator.proceedOTPWithFederatedEmailAddress(EmailOTPAuthenticator.java:576)
    	... 61 more
```

**Cause**

 In the line [1], we are getting the user attributes from only the first authenticated IdP from the list of authenticators. In this case, we will be having 2 authenticated IdP as local and federated in the list since we have configured first-identifier and federated IdP in 2 steps. So it extracting the user attributes from the local IdP which is empty, so passing this error. 

[1] https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L560

### PR DESCRIPTION
**Pull request by Abilashini**
This PR resolves https://github.com/wso2/product-is/issues/4242

This fix provides priority to the authentication step marked as the attribute step when sending email OTP and will not break the previous flow.

### CODE REVIEW

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 1]
```diff
@@ -161,58 +160,191 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+
+            context.setProperty(EmailOTPAuthenticatorConstants.AUTHENTICATION,
+                    EmailOTPAuthenticatorConstants.AUTHENTICATOR_NAME);
             String queryParams = FrameworkUtils.getQueryStringWithFrameworkContextId(
                     context.getQueryParams(), context.getCallerSessionKey(),
                     context.getContextIdentifier());
-            if (isEmailOTPMandatory) {
-                if (log.isDebugEnabled()) {
-                    log.debug("Process the EmailOTP mandatory flow ");
+            // If usecase property is not configured, email OTP will be executed in the below flow (Recommended flow)
```
Comment (hasinthaindrajee) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: This code seems having too long methods from it's beginning. Can we break this down to methods with this effort so that it will be more readable :)

Comment (vihanga-liyanage) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Shall we fix the comment? Should be
If the use case is not properly configured, email OTP will be executed in the below flow (Recommended flow)

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 2]
```diff
@@ -161,58 +160,191 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
-                email = getEmailValueForUsername(username, context);
-                if (StringUtils.isEmpty(email)) {
-                    if (request.getParameter(EmailOTPAuthenticatorConstants.EMAIL_ADDRESS) == null) {
-                        redirectToEmailAddressReqPage(response, context, emailOTPParameters, queryParams, username);
+
+                if (isLocalUser) {
+                    if (isEmailOTPDisableForUser(username, context, emailOTPParameters)) {
+                        if (isEmailOTPMandatory) {
+                            if (log.isDebugEnabled()) {
+                                log.debug("Email OTP is disabled for the user " + username + ", since email OTP is " +
```
Comment (vihanga-liyanage) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Does this log message correct?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 3]
```diff
@@ -161,58 +160,191 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+                                redirectToEmailAddressReqPage(response, context, emailOTPParameters, queryParams,
+                                        username);
+                            } else {
+                                updateEmailAddressForUsername(context, request, username);
+                                email = getEmailValueForUsername(username, context);
+                            }
+                        }
+                        if (StringUtils.isNotEmpty(email)) {
+                            processEmailOTPFlow(request, response, email, username, queryParams, context);
+                        }
```
Comment (vihanga-liyanage) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: What should happen if this IF check fails?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 4]
```diff
@@ -161,58 +160,191 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+
+                    } else {
+                        context.setProperty(EmailOTPAuthenticatorConstants.RECEIVER_EMAIL, email);
+                        processEmailOTPFlow(request, response, email, username, queryParams, context);
+                    }
+
+                } else if (isEmailOTPMandatory) {
+                    if (log.isDebugEnabled()) {
+                        log.debug("Send OTP to federated user is disabled");
```
Comment (vihanga-liyanage) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: How does isEmailOTPMandatory being true connects to this log? Can you please tell me what I'm missing here?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 5]
```diff
@@ -161,58 +160,191 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+                            redirectToEmailAddressReqPage(response, context, emailOTPParameters, queryParams, username);
+                        } else {
+                            updateEmailAddressForUsername(context, request, username);
+                            email = getEmailValueForUsername(username, context);
+                        }
+                    }
+
+                    if (StringUtils.isNotEmpty(email)) {
+                        processEmailOTPFlow(request, response, email, username, queryParams, context);
+                    }
```
Comment (vihanga-liyanage) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:259]: Code duplicated. Line 228:243 and 327:339. Shall we extract this to a private method?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 2 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: if the email OTP is configured as mandatory in the server level, then the user can't disable email OTP. Can be corrected as, 'Since email OTP is mandatory, user cannot disable email OTP'

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 4 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: If for a federated user, 'sendOTPToFederatedEmailAttribute' is not enabled then the email will not be sent. But if email OTP is configured as mandatory, then the authentication should be failed. If it is not mandatory, then email OTP can be skipped.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 3 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: There should not be a case this if check gets fail because if the email is empty, then the above block will be executed and the user will be asked to enter an email address and the user attribute will be updated with the provided email address. But there is a chance if the user tries to update the email with an empty string, this check gets fail. I will correct that.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 5 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:259]: I left it as we planned to revise and remove this block of code. will get it done.

Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:259]: done

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 1 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: done. please verify

Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: this code block will be executed only when the usecase property is not configured. So 'properly' will not make any sense.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 6]
```diff
@@ -982,6 +1030,175 @@ private boolean isEmailOTPDisableForUser(String username, AuthenticationContext
...
+     * @throws AuthenticationFailedException when anything failed during handling email OTP for local user.
+     */
+    private void handleEmailOTPForLocalUser(String username, AuthenticatedUser authenticatedUser,
+                                            AuthenticationContext context, Map<String, String> emailOTPParameters,
+                                            boolean isEmailOTPMandatory, String queryParams,
+                                            HttpServletRequest request, HttpServletResponse response)
+            throws AuthenticationFailedException {
+        try {
+            if (isEmailOTPDisableForUser(username, context, emailOTPParameters)) {
+                if (isEmailOTPMandatory) {
```
Comment (ayshsandu) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Check whether the "isEmailOTPMandatory" first and give priority to the servers preference

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 7]
```diff
@@ -161,58 +160,107 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+                Map<Integer, StepConfig> stepConfigMap = context.getSequenceConfig().getStepMap();
+                Map<ClaimMapping, String> userAttributes = new HashMap<>();
+                String federatedEmailAttributeKey = null;
+                String username = null;
+                boolean isLocalUser = false;
+                // Iterate through the steps to identify from which step the user email address need to extracted
+                for (StepConfig stepConfig : stepConfigMap.values()) {
+                    authenticatedUser = stepConfig.getAuthenticatedUser();
+                    if (authenticatedUser != null && stepConfig.isSubjectAttributeStep()) {
+                        username = authenticatedUser.getUserName();
```
Comment (pulasthi7) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:190]: Do we need to get the username here to get attributes?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 8]
```diff
@@ -161,58 +160,107 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+                if (authenticatedUser == null) {
+                    if (log.isDebugEnabled()) {
+                        log.debug("Cannot find the authenticated user, the username : " + username + " may be null");
+                    }
+                    throw new AuthenticationFailedException
+                            ("Authentication failed!. Cannot find the authenticated user, the username : "
+                                    + username + " may be null");
+                }
+
+                boolean isUserExistence = FederatedAuthenticatorUtil.isUserExistInUserStore(username);
```
Comment (pulasthi7) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:239]: Are we still going with this check?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 6 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: fixed

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 7 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:190]: I get user name here to have a null check later to identify whether the user authenticated step is configured as the attribute step. if the username is null, then the flow will be failed

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 8 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:239]: If the 'usecase' attribute is configured, then this check will be executed. Otherwise, the fixed flow will be executed.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 9]
```diff
@@ -161,58 +160,107 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
+                    if (log.isDebugEnabled()) {
+                        log.debug("Process the EmailOTP mandatory flow ");
+                    }
+                    processEmailOTPMandatory(context, request, response, isUserExistence, username, queryParams,
+                            emailOTPParameters, sendOtpToFederatedEmail);
+
+                } else if (isUserExistence && !isEmailOTPDisableForUser(username, context,
+                        emailOTPParameters)) {
+                    if (log.isDebugEnabled()) {
+                        log.debug("Process the EmailOTP optional flow, but user enable emailOTP as second step ");
```
Comment (ayshsandu) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: add some context information to the debug log. ex: username, otherwise unable to correlate logs to requests.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 10]
```diff
@@ -982,6 +1032,182 @@ private boolean isEmailOTPDisableForUser(String username, AuthenticationContext
...
+            if (isEmailOTPDisableForUser(username, context, emailOTPParameters) && !isEmailOTPMandatory) {
+                if (log.isDebugEnabled()) {
+                    log.debug("Email OTP authentication is skipped for the user " + username +
+                            ". Email OTP is not mandatory and disabled for the user.");
+                }
+                processFirstStepOnly(authenticatedUser, context);
+            } else {
+                String email = getEmailForLocalUser(username, context, emailOTPParameters, queryParams, request,
+                        response);
+                if (StringUtils.isNotEmpty(email)) {
```
Comment (hasinthaindrajee) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:1068]: What if email is empty ? We nether have a log saying it. Let's improve traceability by adding logs.

**Review by pulasthi7 — APPROVED** [review]
Approving as the fix works for this particular fix. However, the code needs a major refactoring as a separate effort outside of this fix. The code is currently almost unreadable due to large number of conditions here and there.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 10 above)
Comment (Abilashini) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:1068]: The purpose of this check is to, skip the next line when the user is requested to provide the email in the UI if the email is not already available for the user. added a log to state that.

**Review by ayshsandu — APPROVED** [review]

**Review by GDRDABARERA — APPROVED** [review]

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 11]
```diff
@@ -161,58 +161,110 @@ protected void initiateAuthenticationRequest(HttpServletRequest request,
...
                 }
-                email = getEmailValueForUsername(username, context);
-                if (StringUtils.isEmpty(email)) {
-                    if (request.getParameter(EmailOTPAuthenticatorConstants.EMAIL_ADDRESS) == null) {
-                        redirectToEmailAddressReqPage(response, context, emailOTPParameters, queryParams, username);
-                    } else {
-                        updateEmailAddressForUsername(context, request, username);
-                        email = getEmailValueForUsername(username, context);
+
+                if (username == null) {
```
Comment (DMHP) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:203]: Can't we use StringUtils here ?
