### PR TITLE
FIX EmailOTP authenticator update the authenticated user unnecessarily

### LINKED ISSUE #5464: EmailOTP authenticator update the authenticated user unnecessarily
**Scenario**
EmailOTP authenticator updates the **authenticated user** unnecessarily after a successful authentication, causing the proceeding authenticators in trouble finding the username.

**Reproducing**
IS 5.7.0
3 Step authentication as-
Basic -> EmailOTP -> TOTP
Subject will be chosen from the Basic authentication step. Upon the login, first 2 steps will execute fine. But once the flow hits the TOTP, below stack trace will be appear.
`ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.step.impl.DefaultStepHandler} -  Error when checking TOTP enabled for the user : null 
org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException: Error when checking TOTP enabled for the user : null
        at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.initiateAuthenticationRequest(TOTPAuthenticator.java:223)
        at org.wso2.carbon.identity.application.authenticator.totp.TOTPAuthenticator.process(TOTPAuthenticator.java:113)`

**Code**
`context.setSubject(AuthenticatedUser.createFederateAuthenticatedUserFromSubjectIdentifier(emailFromProfile));`
[Git link](https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/754576447f1413b2478ff460948c151ce0e5c96e/component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java#L299)

### PR DESCRIPTION
**Pull request by somindatommy**
Resolves https://github.com/wso2/product-is/issues/5464
Approach: Stop updating the authenticated user as the emailFromProfile.

### CODE REVIEW

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 1]
```diff
@@ -296,8 +296,15 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
         if (userToken.equals(contextToken)) {
             context.setProperty(EmailOTPAuthenticatorConstants.OTP_TOKEN, "");
             context.setProperty(EmailOTPAuthenticatorConstants.EMAILOTP_ACCESS_TOKEN, "");
-            String emailFromProfile = context.getProperty(EmailOTPAuthenticatorConstants.RECEIVER_EMAIL).toString();
-            context.setSubject(AuthenticatedUser.createFederateAuthenticatedUserFromSubjectIdentifier(emailFromProfile));
+            Map<Integer, StepConfig> stepConfigMap = context.getSequenceConfig().getStepMap();
+            AuthenticatedUser authenticatedUser = null;
+            for (StepConfig stepConfig : stepConfigMap.values()) {
+                authenticatedUser = stepConfig.getAuthenticatedUser();
```
Comment (Kanapriya) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Since the authenticatedUser is being set in the Authentication context from the identity-extension-utils [1], I hope that we can reuse the method from the identity-extension-utils and retrieve the authenticated user from authentication context instead of iterating through the step configs again. Do you see any limitations to retrieved from the authentication context? 

[1] https://github.com/wso2-extensions/identity-extension-utils/blob/master/component/helper/src/main/java/org/wso2/carbon/extension/identity/helper/FederatedAuthenticatorUtil.java#L422

Comment (somindatommy) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Fixed: 2bc937312bd2e41b01ec55aea2cc1d15f4bdc2a0

Comment (somindatommy) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: The flow is not going through [1] when the `usecase` property is not set. The documentation for emailOTP does not contain any records on adding any properties. Therefore, this approach is preferred. 
Meantime [2] needs to be updated according to [3].

[1] - https://github.com/wso2-extensions/identity-extension-utils/blob/master/component/helper/src/main/java/org/wso2/carbon/extension/identity/helper/FederatedAuthenticatorUtil.java#L422
[2] documentation - https://docs.wso2.com/display/IS570/Configuring+Email+OTP
[3] - https://github.com/wso2-extensions/identity-outbound-auth-email-otp/blob/master/docs/config.md#usecase-definitions

**Review by Kanapriya — APPROVED** [review]

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 2]
```diff
@@ -296,8 +296,15 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
...
+                if (authenticatedUser != null && stepConfig.isSubjectAttributeStep()) {
+                    break;
```
Comment (DMHP) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:306]: If authenticatedUser is null don't we need to throw an exception here?

Comment (somindatommy) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:306]: Fixed: 2b0982e79387f70dcd498d35eb7304b42ee4ee18

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 3]
```diff
@@ -296,8 +297,22 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
...
+                }
+            }
+            if (authenticatedUser == null) {
```
Comment (DMHP) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:309]: Lets simplify the logic here inside the fr loop. We can assign the value to authenticatedUser, if it is the subject step and the authenticated user is not null

Comment (somindatommy) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:309]: Fixed: 538a79627d56a2893bad088599fe197d4e42cc03

**Review by DMHP — APPROVED** [review]

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 4]
```diff
@@ -296,8 +297,20 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
...
             context.setProperty(EmailOTPAuthenticatorConstants.OTP_TOKEN, "");
             context.setProperty(EmailOTPAuthenticatorConstants.EMAILOTP_ACCESS_TOKEN, "");
-            String emailFromProfile = context.getProperty(EmailOTPAuthenticatorConstants.RECEIVER_EMAIL).toString();
-            context.setSubject(AuthenticatedUser.createFederateAuthenticatedUserFromSubjectIdentifier(emailFromProfile));
+            Map<Integer, StepConfig> stepConfigMap = context.getSequenceConfig().getStepMap();
+            AuthenticatedUser authenticatedUser = null;
+            for (StepConfig stepConfig : stepConfigMap.values()) {
+                AuthenticatedUser authenticatedUserInStepConfig = stepConfig.getAuthenticatedUser();
+                if (stepConfig.isSubjectAttributeStep() && authenticatedUserInStepConfig != null) {
+                    authenticatedUser = stepConfig.getAuthenticatedUser();
```
Comment (piraveena) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:305]: can reuse as authenticatedUser= authenticatedUserInStepConfig

Comment (somindatommy) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:305]: Fixed: https://github.com/wso2-extensions/identity-outbound-auth-email-otp/pull/62
