### PR TITLE
Save email address after verifying the email address in multi-step authentication

### LINKED ISSUE #10786: Email OTP/SMS OTP Authenticators saves new email address/mobile number without Verifying
**Describe the issue:**
Multi factor authentication should be enabled with Email OTP/SMS OTP. If a particular user doesn't have the email address/mobile number saved in the profile and when the Email OTP/SMS OTP flow is triggers it will prompt user to privide email address/ mobile number. After that it will save the email address/mobile number in the user profile and then it will send the OTP message to provided email/mobile number. If the user gives an incorrect mobile number then the user won't be able to login to the application.

**How to reproduce:**
1. Enable Email OTP/SMS OTP as multi step authenticator for an application
2. Create a new user withouth filling the email address/ mobile number in the profile
3. Login to the application
4. When the user is prompt to enter the email address/ mobile number then enter an incorrect one
5. With incorrect email/mobile number you won't be able to login to the application

**Expected behavior:**
After capturing the user's email address/ mobile number, the system should first complete the OTP sending and verification flow and then only it should save the email address/ mobile number against the respective user profile

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]

---

### PR DESCRIPTION
**Pull request by chinthakarukshan**
In the current implementation when multi step authentication is enabled and if the user has not specify the email address in the profile, it will prompt user to enter email address and then directly saves it. If user enters an
incorrect email there is no way for the user to change it himself. This implementation will only save the email address once it is confirmed with the OTP code sends.

Resolves https://github.com/wso2/product-is/issues/10786

### CODE REVIEW

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 1]
```diff
@@ -330,6 +331,21 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
             succeededAttempt = validateWithBackUpCodes(context, userToken, authenticatedUser);
         }
 
+        if (succeededAttempt && isLocalUser) {
+            String username = authenticatedUser.toFullQualifiedUsername();
+            try {
+                String userEmail = getEmailValueForUsername(username, context);
+                if (StringUtils.isEmpty(userEmail)) {
```
Comment (emswbandara) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: let's use StringUtils.isBlank here

Comment (emswbandara) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: also shall we move the userEmail validation logic inside updateEmailAddressForUsername method?

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 2]
```diff
@@ -330,6 +331,21 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
...
+                    Object verifiedEmailObject = context.getProperty(EmailOTPAuthenticatorConstants.REQUEST_USER_EMAIL);
+                    if (verifiedEmailObject != null) {
+                        updateEmailAddressForUsername(context, username);
+                    }
+                }
+            } catch (EmailOTPException e) {
+                throw new AuthenticationFailedException("Failed to get the email claim when proceed the EmailOTP flow ", e);
```
Comment (emswbandara) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: its not required to mention 'when proceed the EmailOTP flow' in error message.

Comment (chinthakarukshan) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Fixed the issue

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 1 above)
Comment (chinthakarukshan) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: First issue fixed. Second issue could you please explain it a bit.

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticatorConstants.java [hunk 3]
```diff
@@ -91,6 +91,7 @@
     public static final String USER_NAME = "username";
     public static final String AUTHENTICATED_USER = "authenticatedUser";
     public static final String LOCAL_AUTHENTICATOR = "LOCAL";
+    public static final String REQUEST_USER_EMAIL = "userEmail";
```
Comment (emswbandara) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticatorConstants.java]: let's change this to requestedEmail

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 4]
```diff
@@ -330,6 +331,21 @@ protected void processAuthenticationResponse(HttpServletRequest request, HttpSer
...
+            try {
+                String userEmail = getEmailValueForUsername(username, context);
+                if (StringUtils.isBlank(userEmail)) {
+                    Object verifiedEmailObject = context.getProperty(EmailOTPAuthenticatorConstants.REQUEST_USER_EMAIL);
+                    if (verifiedEmailObject != null) {
+                        updateEmailAddressForUsername(context, username);
+                    }
+                }
+            } catch (EmailOTPException e) {
+                throw new AuthenticationFailedException("Failed to get the email claim", e);
```
Comment (emswbandara) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: lets add some context info.
Failed to get the email claim for user: + username

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticatorConstants.java (hunk 3 above)
Comment (chinthakarukshan) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticatorConstants.java]: Fixed this issue

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java (hunk 4 above)
Comment (chinthakarukshan) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java]: Fixed the issue

**Review by emswbandara — APPROVED** [review]

**Review by rksk — APPROVED** [review]
