### PR TITLE
Decouple EmailOTPAuthenticator from extending OpenIDConnectAuthenticator

### LINKED ISSUE #10782: Email OTP authentication does not work, Blank Page after entering the OTP code
**Describe the issue:**
Email OTP authentication does not work, Blank Page after entering the OTP code. 

We have overridden the process method in OpenIDConnectAuthenticator[1], EmailOTPAuthenticator extends the OpenIDConnectAuthenticator, the process method introduced to OpenIDConnectAuthenticator causes the authentication to go to an INCOMPLETE state in the Email OTP flow.

**How to reproduce:**
Configure Email OTP and enter a valid/invalid OTP code.

**Environment information**  **:**
 - Product Version: [IS 5.10.0]

[1]https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/87
---

### PR DESCRIPTION
**Pull request by Thumimku**
## Purpose
Fixes https://github.com/wso2/product-is/issues/10782

Description
Since these 2 authenticators serve 2 different purposes (OpenIDConnectAuthenticator for identity federation and Email OTP for MFA),  we need to decouple them

### CODE REVIEW

File: component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java [hunk 1]
```diff
@@ -2005,14 +2005,6 @@ public String getContextIdentifier(HttpServletRequest request) {
         return request.getParameter("sessionDataKey");
     }
 
-    /**
-     * Check ID token in EmailOTP OAuth.
-     */
-    @Override
-    protected boolean requiredIDToken(Map<String, String> authenticatorProperties) {
```
Comment (emswbandara) [inline component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:2012]: we shouldn't remove protected methods. Let's remove the override tag and mark it as deprecated.

Comment (Thumimku) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:2012]: ACK

Comment (emswbandara) [reply component/authenticator/src/main/java/org/wso2/carbon/identity/authenticator/emailotp/EmailOTPAuthenticator.java:2012]: we can add      @Deprecated annotation as well.

**Review by emswbandara — APPROVED** [review]
